[build]
  publish = "_site"
  command = "npm run build"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    Content-Security-Policy = "script-src 'self' https://lightpositive.hu/ https://www.lightpositive.hu/ https://identity.netlify.com https://cdn.jsdelivr.net https://www.googletagmanager.com https://www.google-analytics.com https://www.google.com/ https://www.gstatic.com/ 'unsafe-inline';" 
    Content-Security-Policy = "img-src 'self' *.cloudinary.com/ *.lightpositive.hu/ data:;"
    Content-Security-Policy = "style-src 'self' https://fonts.googleapis.com 'unsafe-inline';"
    Content-Security-Policy = "font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;"
    Content-Security-Policy = "frame-src 'self' https://www.google.com/;"
    Content-Security-Policy = "connect-src 'self' https://www.google-analytics.com https://www.google.com/ https://www.gstatic.com/ region1.google-analytics.com"
